import { Geist, Geist_Mono, Mona_Sans } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";

import "primereact/resources/themes/lara-light-cyan/theme.css";

import { Providers } from "@/utils/Providers";
import store from "@/store/store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers store={store}>{children}</Providers>
      </body>
    </html>
  );
}
